my_num: 1
terminate called after throwing an instance of 'std::runtime_error'
  what():  No client after one minute
Aborted (core dumped)
